"""Cascade all in comments-task relationship

Revision ID: fb02bef0fc5a
Revises: e2531efa95d0
Create Date: 2025-08-07 10:33:54.417992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb02bef0fc5a'
down_revision: Union[str, Sequence[str], None] = 'e2531efa95d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
